const STORAGE_SETTING_NAME = "cs-settings";
const STORAGE_SERIES_NAME = "cs-series-items";
const STORAGE_NEWEST_NAME = "cs-newest-posts";
const STORAGE_POSTS_NAME = "cs-all-posts";

const INCOM_ONMOUNTED_EVENT_NAME = "incomMounted";
const POSTS_FETCHED_EVENT_NAME = "postsFetched";

export {
  STORAGE_SETTING_NAME,
  STORAGE_SERIES_NAME,
  STORAGE_NEWEST_NAME,
  STORAGE_POSTS_NAME,
  POSTS_FETCHED_EVENT_NAME,
  INCOM_ONMOUNTED_EVENT_NAME,
};
